sudo: false
language: node_js
node_js:
  - stable
services:
  - mongodb
cache:
  directories:
    - node_modules
install:
  - npm install --no-optional
before_script:
  - npm info dredd version
  - dredd
before_install:
  - npm install -g dredd@5.1.7
  - npm install -g dredd@5.1.7
  - npm install -g dredd@5.1.7
